### ISSUE TITLE
For review

### ISSUE THREAD

**Issue by yudai-yokose** [yokose1991/Fishingram#46]
## 各種情報
- サービス名
Fishingram

- サービスURL
https://fishingram-3dead5b2b24d.herokuapp.com/

- Git Hub
https://github.com/Yudai-Yokose/Fishingram

- サービス概要
  - 本サービスは、釣り人の釣果記録を支援するツール系サービスです。
  - 魚の写真や位置情報など、釣果の記録をシンプルな操作性で実現します。
  - 自分だけの釣果記録を作り上げていく感覚を提供することで、釣行と記録のサイクルに繋げます。

- MVPで検証する事柄
  - [x] アカウント登録ができるか
  - [x] ログインができるか
  - [x] googleアカウントでの認証ができるか
  - [x] 釣果の投稿、編集ができるか
  - [x] 日記の投稿、編集ができるか
  - [x] コメントの投稿、編集ができるか
  - [x] いいね、または取り消しができるか
  - [x] 位置情報を取得できるか
  - [x] ユーザー情報の編集、削除ができるか

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 釣果の記録が手軽にできる記録機能
- [x] 釣行の振り返りができる日記機能
- [x] Turboを活用したインタラクティブな操作性とユーザーエクスペリエンスの向上
- [x] ダークモードによる視認性の向上と電力消費の抑制
- [x] 緩やかなSNS機能
- [x] ユーザー認証機能
- [x] Googleアカウントでのユーザー認証機能

**Comment by tarakish** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
